const jobData = [
  {
    id: 1,
    companyName: "Tech Corp",
    jobTitle: "Junior Developer",
    location: "New York",
    salary: "$50k-$70k",
    tags: "Part-time",
    distance: 2.5,
    logoColor: "bg-blue-500",
    companyLogo: "T"
  },
  {
    id: 2,
    companyName: "Delivery Plus",
    jobTitle: "Delivery Driver",
    location: "Los Angeles",
    salary: "$30k-$40k",
    tags: "Hourly",
    distance: 7.3,
    logoColor: "bg-green-500",
    companyLogo: "D"
  },
  {
    id: 3,
    companyName: "Clean Services",
    jobTitle: "Cleaning Staff",
    location: "Chicago",
    salary: "$25k-$35k",
    tags: "Hourly",
    distance: 4.8,
    logoColor: "bg-purple-500",
    companyLogo: "C"
  },
  {
    id: 4,
    companyName: "Retail Store",
    jobTitle: "Shop Assistant",
    location: "Boston",
    salary: "$28k-$38k",
    tags: "Weekend Jobs",
    distance: 12.5,
    logoColor: "bg-orange-500",
    companyLogo: "R"
  },
  {
    id: 5,
    companyName: "Café & Kitchen",
    jobTitle: "Barista",
    location: "Seattle",
    salary: "$26k-$36k",
    tags: "Part-time",
    distance: 8.9,
    logoColor: "bg-red-500",
    companyLogo: "K"
  },
  {
    id: 6,
    companyName: "Event Masters",
    jobTitle: "Event Coordinator",
    location: "Miami",
    salary: "$32k-$42k",
    tags: "Seasonal",
    distance: 25.2,
    logoColor: "bg-pink-500",
    companyLogo: "E"
  }
];

export default jobData;

export const INITIALJOBS = [
  {
    id: 1,
    workPlaceName: "Tvs Ltd",
    jobTitle: "Customer Support Executive",
    jobType: "part-time",
    jobStatus: "blocked",
    workingTimeStart: "20:00",
    workingTimeEnd: "02:00",
    salaryMin: 18000,
    salaryMax: 25000,
    salaryType: "monthly",
    jobSummary: "Handle customer queries via calls and chat.",
    responsibilities: [
      "Answer customer calls",
      "Resolve issues"
    ],
    requiredSkills: ["Communication", "Problem Solving"],
    city: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    workplaceAddress: "Gandhipuram, Coimbatore",
    latitude: 11.0168,
    longitude: 76.9558,
    applications: 24,
    postedDate: "2026-01-15"
  },
  {
    id: 2,
    workPlaceName: "Quick Delivery",
    jobTitle: "Delivery Assistant",
    jobType: "hourly",
    jobStatus: "rejected",
    workingTimeStart: "17:00",
    workingTimeEnd: "21:00",
    salaryMin: 120,
    salaryMax: 150,
    salaryType: "hourly",
    jobSummary: "Deliver parcels within nearby areas.",
    responsibilities: ["Pick up orders", "Timely delivery"],
    requiredSkills: ["Two-Wheeler License"],
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    workplaceAddress: "Hitech City, Hyderabad",
    latitude: 17.4483,
    longitude: 78.3915,
    applications: 18,
    postedDate: "2026-01-14"
  },
  {
    id: 3,
    workPlaceName: "Cafe Aroma",
    jobTitle: "Cafe Helper",
    jobType: "part-time",
    jobStatus: "active",
    workingTimeStart: "07:00",
    workingTimeEnd: "12:00",
    salaryMin: 500,
    salaryMax: 700,
    salaryType: "daily",
    jobSummary: "Assist customers and maintain cleanliness.",
    responsibilities: ["Serve customers", "Clean tables"],
    requiredSkills: ["Basic Communication"],
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    workplaceAddress: "Anna Nagar, Chennai",
    latitude: 13.0878,
    longitude: 80.2785,
    applications: 15,
    postedDate: "2026-01-13"
  },
  {
    id: 4,
    workPlaceName: "Retail Hub",
    jobTitle: "Shop Assistant",
    jobType: "weekend-time",
    jobStatus: "active",
    workingTimeStart: "10:00",
    workingTimeEnd: "18:00",
    salaryMin: 600,
    salaryMax: 800,
    salaryType: "daily",
    jobSummary: "Assist customers during weekend rush.",
    responsibilities: ["Customer handling", "Stock arrangement"],
    requiredSkills: ["Customer Interaction"],
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    workplaceAddress: "Hinjewadi, Pune",
    latitude: 18.5913,
    longitude: 73.7389,
    applications: 22,
    postedDate: "2026-01-12"
  },
  {
    id: 5,
    workPlaceName: "Event Masters",
    jobTitle: "Event Support Staff",
    jobType: "season-time",
    jobStatus: "pending",
    workingTimeStart: "14:00",
    workingTimeEnd: "22:00",
    salaryMin: 800,
    salaryMax: 1000,
    salaryType: "daily",
    jobSummary: "Support event setup and crowd management.",
    responsibilities: ["Setup support", "Crowd assistance"],
    requiredSkills: ["Team Work"],
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    workplaceAddress: "Andheri East, Mumbai",
    latitude: 19.1136,
    longitude: 72.8697,
    applications: 30,
    postedDate: "2026-01-11"
  },
  {
    id: 6,
    workPlaceName: "City Clean Services",
    jobTitle: "Cleaning Helper",
    jobType: "hourly",
    jobStatus: "active",
    workingTimeStart: "06:00",
    workingTimeEnd: "10:00",
    salaryMin: 100,
    salaryMax: 130,
    salaryType: "hourly",
    jobSummary: "Clean office and commercial spaces.",
    responsibilities: ["Floor cleaning", "Waste disposal"],
    requiredSkills: ["Basic Discipline"],
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    workplaceAddress: "Yelahanka, Bangalore",
    latitude: 13.1007,
    longitude: 77.5963,
    applications: 12,
    postedDate: "2026-01-10"
  }
];

  export const INITIALCANDIDATES = [
  {
    id: 1,
    name: "Rajesh Kumar",
    email: "rajesh@email.com",
    phone: "+919876543210",
    profile: null,
    position: "Maintenance Worker",
    appliedDate: "2026-01-16",
    status: "pending",
    address: "Kozhikode, Kerala, India",
    city: "Kozhikode",
    state: "Kerala",
    age: 28,
    language: "English, Hindi, Malayalam",
    education: "Diploma / ITI",
    skills: ["Plumbing", "Electrical Work"],
    about: "Experienced maintenance worker"
  },
  {
    id: 2,
    name: "Anita Sharma",
    email: "anita@email.com",
    phone: "+919812345678",
    profile: null,
    position: "Customer Support Executive",
    appliedDate: "2026-01-15",
    status: "pending",
    address: "Indiranagar, Bangalore, India",
    city: "Bangalore",
    state: "Karnataka",
    age: 26,
    language: "English, Hindi",
    education: "Bachelor’s Degree",
    skills: ["Customer Handling", "Communication"],
    about: "Customer support executive with strong communication skills."
  },
  {
    id: 3,
    name: "Rahul Verma",
    email: "rahul@email.com",
    phone: "+919823456789",
    profile: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    position: "Delivery Assistant",
    appliedDate: "2026-01-14",
    status: "accepted",
    address: "Hitech City, Hyderabad, India",
    city: "Hyderabad",
    state: "Telangana",
    age: 24,
    language: "English, Telugu",
    education: "Intermediate",
    skills: ["Two-Wheeler Driving", "Time Management"],
    about: "Reliable delivery assistant with city route knowledge."
  },
  {
    id: 4,
    name: "Sneha Iyer",
    email: "sneha@email.com",
    phone: "+919834567890",
    profile: null,
    position: "Cafe Helper",
    appliedDate: "2026-01-13",
    status: "pending",
    address: "Anna Nagar, Chennai, India",
    city: "Chennai",
    state: "Tamil Nadu",
    age: 22,
    language: "English, Tamil",
    education: "Bachelor’s Degree",
    skills: ["Customer Service", "Cleaning"],
    about: "Energetic cafe helper with good customer interaction skills."
  },
  {
    id: 5,
    name: "Amit Patil",
    email: "amit@email.com",
    phone: "+919845678901",
    profile: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    position: "Shop Assistant",
    appliedDate: "2026-01-12",
    status: "pending",
    address: "Hinjewadi, Pune, India",
    city: "Pune",
    state: "Maharashtra",
    age: 27,
    language: "English, Marathi",
    education: "Diploma",
    skills: ["Sales", "Stock Handling"],
    about: "Shop assistant with experience in retail sales."
  },
  {
    id: 6,
    name: "Neha Gupta",
    email: "neha@email.com",
    phone: "+919856789012",
    profile: null,
    position: "Event Support Staff",
    appliedDate: "2026-01-11",
    status: "pending",
    address: "Andheri East, Mumbai, India",
    city: "Mumbai",
    state: "Maharashtra",
    age: 29,
    language: "English, Hindi",
    education: "Bachelor’s Degree",
    skills: ["Team Work", "Crowd Handling"],
    about: "Event support staff experienced in managing large gatherings."
  },
  {
    id: 7,
    name: "Suresh Naik",
    email: "suresh@email.com",
    phone: "+919867890123",
    profile: null,
    position: "Cleaning Helper",
    appliedDate: "2026-01-10",
    status: "accepted",
    address: "Yelahanka, Bangalore, India",
    city: "Bangalore",
    state: "Karnataka",
    age: 34,
    language: "English, Kannada",
    education: "10th Pass",
    skills: ["Cleaning", "Discipline"],
    about: "Dedicated cleaning helper with office cleaning experience."
  },
  {
    id: 8,
    name: "Priya Menon",
    email: "priya@email.com",
    phone: "+919878901234",
    profile: null,
    position: "Office Assistant",
    appliedDate: "2026-01-09",
    status: "pending",
    address: "Kakkanad, Kochi, India",
    city: "Kochi",
    state: "Kerala",
    age: 25,
    language: "English, Malayalam",
    education: "Bachelor’s Degree",
    skills: ["Documentation", "Basic Computer Knowledge"],
    about: "Office assistant with good documentation and computer skills."
  },
  {
    id: 9,
    name: "Vikram Singh",
    email: "vikram@email.com",
    phone: "+919889012345",
    profile: null,
    position: "Warehouse Helper",
    appliedDate: "2026-01-08",
    status: "rejected",
    address: "Bhiwandi, Mumbai, India",
    city: "Mumbai",
    state: "Maharashtra",
    age: 31,
    language: "English, Hindi",
    education: "12th Pass",
    skills: ["Loading & Unloading", "Inventory Support"],
    about: "Warehouse helper experienced in handling goods and stock."
  }
];



  export const INITIALEMPLOYER = [
  {
    id: 1,
    employerName: "Sharma Brothers Cleaning Services",
    workPlaceName: "Downtown Office Complex",
    contactNo: "+91 98765 43210",
    email: "contact@sharmabrothers.com",
    hiringPosition: "Cleaning Staff",
    postedDate: "15-Jan-2025",
    profileImage: null,
    city: "Bangalore",
    state: "Karnataka",
    aboutDescription:
      "Professional cleaning services for offices and commercial buildings.",
    jobStats: {
      totalJobsPosted: 23,
      activeJobs: 5,
    },
  },
  {
    id: 2,
    employerName: "Tea House Café",
    workPlaceName: "MG Road Branch",
    contactNo: "+91 87654 32109",
    email: "jobs@teahouse.in",
    hiringPosition: "Café Helper",
    postedDate: "10-Jan-2025",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tea",
    city: "Bangalore",
    state: "Karnataka",
    aboutDescription:
      "A popular café serving premium tea and snacks with multiple branches.",
    jobStats: {
      totalJobsPosted: 12,
      activeJobs: 3,
    },
  },
  {
    id: 3,
    employerName: "Express Delivery Co.",
    workPlaceName: "Central Warehouse",
    contactNo: "+91 76543 21098",
    email: "hr@expressdeliver.com",
    hiringPosition: "Delivery Boy",
    postedDate: "08-Jan-2025",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Express",
    city: "Chennai",
    state: "Tamil Nadu",
    aboutDescription:
      "Fast and reliable last-mile delivery services across the city.",
    jobStats: {
      totalJobsPosted: 30,
      activeJobs: 8,
    },
  },
  {
    id: 4,
    employerName: "Fashion Tailor Studio",
    workPlaceName: "Market Street",
    contactNo: "+91 65432 10987",
    email: "tailor@fashionstudio.com",
    hiringPosition: "Tailor",
    postedDate: "20-Dec-2024",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tailor",
    city: "Hyderabad",
    state: "Telangana",
    aboutDescription:
      "Custom tailoring studio specializing in men’s and women’s fashion.",
    jobStats: {
      totalJobsPosted: 9,
      activeJobs: 2,
    },
  },
  {
    id: 5,
    employerName: "Silk Dress Shop",
    workPlaceName: "Fashion Mall",
    contactNo: "+91 54321 09876",
    email: "hiring@silkdress.in",
    hiringPosition: "Dress Shop Worker",
    postedDate: "18-Dec-2024",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Silk",
    city: "Coimbatore",
    state: "Tamil Nadu",
    aboutDescription:
      "Retail store specializing in silk sarees and traditional clothing.",
    jobStats: {
      totalJobsPosted: 15,
      activeJobs: 4,
    },
  },
];


export const INITIAL_EMPLOYER_PROFILE = {
  shopName: "TechVista Solutions",
  city: "Bangalore",
  state: "Karnataka",
  phoneNumber: "+919876543210",
  email: "contact@techvista.com",
  aboutDescription: "Leading software development company specializing in web and mobile applications. We build innovative solutions for startups and enterprises.",
  profileImage: null,
  jobStats: {
    totalJobsPosted: 23,
    activeJobs: 5
  }
};
